### ISSUE TITLE
TRAPI 1.2 -> 1.3 migration

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#450]
The changelog for 1.2 -> 1.3 is at https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/ChangeLog.md, and the proposed timing is in https://github.com/NCATSTranslator/ReasonerAPI/issues/329:

**EDIT**: Updated timeline below as of 2022-06-24
```
Jun 30 TRAPI 1.3-beta declared ready for implementation
Jul 14 TRAPI 1.3-beta implemented by KPs at test endpoints
Jul 28 TRAPI 1.3-beta implemented by ARAs at test endpoints
Aug 11 TRAPI 1.3-beta implemented by ARS at test endpoints
Aug 25 TRAPI 1.3 released as final
       All TRAPI 1.3 instances released to prod endpoints
       All TRAPI 1.2 instances deleted from prod 1.2 endpoints
```

After the relay, we'll need to do an analysis of these changes.

**Comment by andrewsu** [comment]
Pasting the current changelog as a checklist below.  Let's check off the simple things here, and create and link new issues for anything needing more coordination.

- [ ] Add test_data_location in x-trapi https://github.com/NCATSTranslator/ReasonerAPI/pull/339/files
- [ ] Add flag for knowledge_type flag for Creative Mode https://github.com/NCATSTranslator/ReasonerAPI/pull/331/files
- [ ] Add support for Qualifiers in KGs and queries https://github.com/NCATSTranslator/ReasonerAPI/pull/330/files
- [ ] Add knowledge_types support to /meta_knowledge_graph https://github.com/NCATSTranslator/ReasonerAPI/pull/333/files
- [ ] Add === operator to Constraint https://github.com/NCATSTranslator/ReasonerAPI/commit/875112b7a349c9f8e89bb5660725af5c895c9a24
- [ ] Clarified meaning of batch_size_limit https://github.com/NCATSTranslator/ReasonerAPI/commit/ad3c16a3ecc085cc041b0ebbeeb7f0803e054fd0
- [ ] Misc documentation fixes
- [ ] Add NodeBinding.query_id property. Optional but a substantial change to current practice https://github.com/NCATSTranslator/ReasonerAPI/commit/dc6e864af5e498f7e420318b16be7d4a2f9a03ef
- [ ] Clarification on expectations for /meta_knowledge_graph for KPs and ARAs https://github.com/NCATSTranslator/ReasonerAPI/commit/e2ed87aa4f02dac55dcbd8eac7e190b8c188fbdd
- [ ] Permit unlimited recursion of attributes https://github.com/NCATSTranslator/ReasonerAPI/commit/6ec8ea28f3262ac163803622017bb651a4adac33
- [ ] Added NodeBinding.Attributes
- [ ] Clarification on how to properly to specify KP "allowlist"s and "denylist"s via constraints https://github.com/NCATSTranslator/ReasonerAPI/commit/82218fc86be74755ec1ffa9b8679eac0075df364
- [ ] Clarification on previously-agreed handling of QNode and QEdge additional properties https://github.com/NCATSTranslator/ReasonerAPI/commit/85fefd44925652a5b2e9648fef1d6c70c5099ea9

I added an agenda item to do an initial discussion during our 2022-06-29 team meeting, but likely we'll need a dedicated meeting among key people...

**Comment by colleenXu** [comment]
FYI the comment with the timeline as of 6-24: https://github.com/NCATSTranslator/ReasonerAPI/issues/329#issuecomment-1165191070

**Comment by colleenXu** [comment]
Note that TRAPI 1.3 isn't frozen yet, so changes are still incoming 
* https://github.com/NCATSTranslator/ReasonerAPI/pull/340/files
* https://github.com/NCATSTranslator/ReasonerAPI/pulls

**Comment by colleenXu** [comment]
Frozen June 30th

Pasting from internal Translator [Slack](https://ncatstranslator.slack.com/archives/CSS752SB0/p1656702232706879):

> Hi everyone @here, TRAPI 1.3-beta was finished yesterday, with all final changes merged into the schema. You'll find the TRAPI 1.3-beta schema here: https://github.com/NCATSTranslator/ReasonerAPI/tree/1.3 (Note that this is the "1.3" branch, not that master branch)
> It is ready for implementations according to our schedule: https://github.com/NCATSTranslator/ReasonerAPI/issues/329#issuecomment-1165191070
> Please update the tracking sheet starting in column AL in https://docs.google.com/spreadsheets/d/1LEV3FyXBt3xm4bC5TQkVbrZalrr6OV2LnPtuLj1RVB4/edit#gid=1034097652 as you complete your implementations.
> The ChangeLog to guide your updates is here: https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/ChangeLog.md
> TRAPI 1.3-beta is still in the beta phase during implementations, meaning that we can still change something if we find we made a mistake. TRAPI 1.3 will be declared final and be released once implementations have tested it to make sure we got it right.

**Comment by colleenXu** [comment]
My analysis of the changelog AND 1.2 -> 1.3 comparison, Part 1

We are now using this comment as the "primary" source of "what we are doing":

This has some tasks that aren't in the changelog 

EDIT: DONE 

## Highest Priority

aka things are going to break big if we don't do this

### Mostly Jackson / a dev

A. [Add knowledge_types support to /meta_knowledge_graph](https://github.com/NCATSTranslator/ReasonerAPI/pull/333/files). This is an optional property on MetaEdges, but...
* we want BTE to handle this if it shows up in TRAPI KP /meta_knowledge_graphs. Current implementation: not tested yet (by connecting to TRAPI 1.3 KPs that have these situations)
   * [x] if a MetaEdge has specifically "knowledge_types": ["inferred"] (1-element array), this MetaEdge is only for creative-mode. We shouldn't ingest these MetaEdges (ignore).  
      * status: NOT IRL TESTED, since I haven't found a TRAPI 1.3 KP that we use that also has this. 
   * [x] we ingest the MetaEdge (proceed with previous behavior) in all other cases
      * status: IRL TESTED, SEEMS TO WORK. We ingest TRAPI 1.3 KPs that have the property but the value is `null` (Automat stuff) and don't have the property (COHD). 
      * the property may be missing
      * the "knowledge_types" array has "lookup" as one of its elements
* [x] we want BTE the ARA (v1/meta_knowledge_graph endpoint) to add this property to the MetaEdges it currently advertises, if we can do creative-mode on them. 
    * status: DONE. current implementation: 
        * draws from creative-mode templateGroups.json spec (in query-handler module). 
        * Doesn't do any biolink-model expansion up the hierarchy. 
        * Adds MetaEdges that we can only do as "inferred". 
       * don't do it on api-specific / team-specific endpoints, since those are basically KPs and almost all will not be able to successfully run templates (they don't have the MetaEdges for it)
           * Andrew: in the future, we may want the Service Provider team endpoint to also advertise that it can do creative-mode...
           * Tyler Beck (link-brokers) has said that KPs are not expected to do creative-mode (internal Translator slack [link](https://ncatstranslator.slack.com/archives/C013Q5TVC87/p1658494801925459))

<br>

B. [Add NodeBinding.query_id property. Optional but a substantial change to current practice](https://github.com/NCATSTranslator/ReasonerAPI/commit/dc6e864af5e498f7e420318b16be7d4a2f9a03ef) This is TRAPI trying to handle ontology-based expansion.
* This is confusing! Tenative understanding, if a TRAPI KP does ontology-based expansion...
   * result node_bindings.id will NOT match what the QNode is (main id or synonyms / equivalent-IDs)
   * result node_bindings.query_id should exist and will match what the QNode is
* [x] Check that BTE gracefully ignores result node_bindings.query_id if it exists. Keep the current behavior: when results have node_bindings.id that don't match the QNode, we end up having "undefined" results/records and dropping them 
   * status: NOT IRL TESTED, since I haven't found a TRAPI 1.3 KP that we use that also has values for `query_id`. Automat KPs do have this property (value is `null`), and BTE has no issue with this. 
* If BTE is going to do ontology-based expansion "regularly" (see  [open](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/366) [issues](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/196) that @ericz1803 is working on), we need to deep-dive on this topic:
   * status: waiting
   * do we adjust records, results-assembly (handling, reporting results) for non-matching node_binding.id and adding query_id? 
      * check: is this for all endpoints? (api-specific, team-specific that act as "KP", vs general that acts as "ARA")
   * Revisit the decision above: should BTE keep and handle results from TRAPI KPs that have non-matching node_binding.id and also have query_id?

<br>

EDIT: Don't worry about this. Looks like the "all implied ancestor relationships" part will be removed. https://github.com/NCATSTranslator/ReasonerAPI/pull/354

~C. [Clarification on expectations for /meta_knowledge_graph for KPs and ARAs](https://github.com/NCATSTranslator/ReasonerAPI/commit/e2ed87aa4f02dac55dcbd8eac7e190b8c188fbdd).~
* ~[ ] Andrew will ask TRAPI team about this:~
   * ~does this involve biolink-expansion to ancestors for subject-category, predicate, and object-category? Since then 1 MetaEdge like SmallMolecule-treats-Disease becomes 4 * 5 * 4 = 80 MetaEdges...~
   * ~we can't tell what is a specific thing the KP has vs what's an "implied ancestor relationship"~
   * ~This is all a problem since we (as an ARA) [already](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/167) [handle](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/102) biolink-model "expansion to descendants".....so with the current behavior, there would be a lot of redundant sub-querying of TRAPI KPs by BTE if they advertise all ancestral relationships...~
* ~What do we do, if other TRAPI KPs are going to do this? And what do we do with our own /meta_knowledge_graph endpoints?~

Notes:
* MetaEdges in the basic endpoint that apply to "lookup" and "inferred": 
   * SmallMolecule -(treats)-> Disease
   * SmallMolecule -(treats)-> PhenotypicFeature
   * ChemicalEntity -(treats)-> Disease
   * ChemicalEntity -(treats)-> PhenotypicFeature
   * Drug -(treats)-> Disease
   * MolecularMixture -(treats)-> Disease (since Drug is one of its children)
   * MolecularMixture -(treats)-> PhenotypicFeature 
* Notice "Drug - treats - PhenotypicFeature" would be something we support in "inferred" mode but we don't have a "lookup" MetaEdge for it
* At the moment, we don't include "ComplexMolecularMixture" (has a treats Disease + treats PhenotypicFeature)
* Polypeptide?

**Comment by colleenXu** [comment]
These are things that still need clarification!!! Related to getting the Highest Priority stuff done (above post)

<br>

EDIT: based on Translator Slack discussions and this [update](https://github.com/NCATSTranslator/ReasonerAPI/issues/329#issuecomment-1176914073), it seems like the July 14 (KPs) / July 28 (ARAs) is for non-ITRB dev. 

We have this done.

---

EDIT: at the moment, it seems like we will all move to TRAPI 1.3, without keeping TRAPI 1.2. We've decided not to make new registrations / update our current registrations, to advertise the TRAPI 1.3 version. 


---

Old notes: 

I think we still have questions on how deployment to ITRB instances will work (the August 11 / August 25 deadlines), since it's not clear to us how we'll keep both 1.2 and 1.3 instances...

Note the ITRB / non-ITRB instances:
* non-ITRB "dev" (we control)
* ITRB test "testing"
* ITRB CI aka "staging"
* ITRB prod aka "prod"


This [reply](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1657155003169159) from Eric Deutsch (internal Translator Slack link) seems to say:
* it's still not clear if we have to keep 1.2 and 1.3 at the same time. Depends on UI/MVP rollout?
* if we do need to keep both, he thinks "different instances are on different TRAPI versions" will be the way...
   * He mentions [here](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1657166175783259) some concern that in September, some teams will not support 1.2 properly (because they have already migrated to 1.3?) 

[we may need to keep the 1.2 endpoints even after TRAPI 1.3 deadlines pass](https://github.com/NCATSTranslator/ReasonerAPI/issues/329#issuecomment-1171485269)
* does this mean different instances (see above) are on different TRAPI versions? 
* Or does this mean each instance has both 1.2 and 1.3 endpoints?
   * this would affect the urls we have for endpoints?

---

And some expectations (copied from Eric Deutsch / internal Translator [Slack](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1657241664649229?thread_ts=1657202034.727659&cid=C0156TX0VB2) with some editing):

the minimal bar here for TRAPI 1.3 implementation here is that 

* all emitted TRAPI be 1.3 compliant (and I think a schema-valid TRAPI 1.2 document is also a schema-valid TRAPI 1.3 document, so this is a low bar), AND that 
* your system not crash or yield a validation error when handed TRAPI 1.3 document with a TRAPI 1.3 optional feature. 
* Whether you handle those optional TRAPI 1.3 features in a optimal way will not initially be subject to review, but hopefully as time goes on and we flesh out these features, expectations may increase.

**Comment by colleenXu** [comment]
My analysis of the changelog AND 1.2 -> 1.3 comparison, Part 2

## Middle Priority

aka little things may break if we don't do this, but overall BTE will work

### Mostly Jackson / a dev

[Add flag for knowledge_type flag for Creative Mode](https://github.com/NCATSTranslator/ReasonerAPI/pull/331/files)
* [x] DONE. check that BTE does "normal / non-creative-mode" behavior when a QEdge has "knowledge_type:lookup". ~Should be a quick / small task?~ Jackson confirmed [below](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1180766198)
* Note: already implemented for creative-mode (doing "creative-mode" when a QEdge has "knowledge_type:inferred")

<br>

[Add support for Qualifiers in KGs and queries](https://github.com/NCATSTranslator/ReasonerAPI/pull/330/files
). Involves "constraints" stuff. 
* ~[x] Changing current "constraints" to "attribute_constraints"~
* [x] DONE: [revert this change](https://suwulab.slack.com/archives/CC218TEKC/p1658524548545949)....since QNode has "constraints" (and that's what we had implemented so far) vs QEdge has "attribute_constraints" / "qualifier_constraints"

EDIT: moving text that was below on test_data_location to other issues. 

## Lower Priority

aka only breaks something very small, it's optional, or we don't really plan on supporting this

### Mostly Jackson / a dev

[Clarification on previously-agreed handling of QNode and QEdge additional properties](https://github.com/NCATSTranslator/ReasonerAPI/commit/85fefd44925652a5b2e9648fef1d6c70c5099ea9)
* current implementation: We had decided to modify smartapi yaml to set additionalProperties to `false`. BTE would then give schema-validation errors on the Query. However, I ended up setting it only for QEdge and not QNode, since people (including me) often put a "name" property there to remember what the IDs are for. 

* [x] BTE stops execution, has logs when someone tries to query using QEdge.attribute_constraints, QEdge.qualifier_constraints, QNode.constraints. 
    * status: IRL TESTED. see queries below (collapsed)
    * still involves [clarification](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1660099244138709) on what is the proper term for the QNode thing. 

<details>
<summary>QEdge attribute_constraints (not semmeddb as knowledge source)</summary>
trying not to use semmeddb on one of the edges. 

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "creativeQuerySubject": {
                    "categories":["biolink:ChemicalEntity"]
                },
                "nA": {
                    "categories":["biolink:DiseaseOrPhenotypicFeature"],
                    "is_set": true
                },
                "creativeQueryObject": {
                    "ids":["MONDO:0005147"],
                    "categories":["biolink:DiseaseOrPhenotypicFeature"],
                    "name": "type 1 dm"
               }
            },
            "edges": {
                "eA": {
                    "subject": "creativeQuerySubject",
                    "object": "nA",
                    "predicates": ["biolink:treats"],
                    "attribute_constraints": [{
                        "id": "biolink:knowledge_source", 
                        "name": "knowledge source",
                        "not": true, 
                        "operator": "==",
                        "value": "infores:semmeddb"
                        }]
                },
                "eB": {
                    "subject": "nA",
                    "object": "creativeQueryObject",
                    "predicates": ["biolink:subclass_of"]
                }
            }
        }
    }
}
```

</details>

<details>
<summary>QEdge qualifier_constraints (Gene expression)</summary>
trying to find chem that regulate the gene's expression

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "creativeQuerySubject": {
                    "categories":["biolink:ChemicalEntity"]
                },
                "nA": {
                    "categories":["biolink:Gene"],
                    "is_set": true
                },
                "creativeQueryObject": {
                    "ids":["MONDO:0007035"],
                    "categories":["biolink:DiseaseOrPhenotypicFeature"],
                    "name": "acanth"
               }
            },
            "edges": {
                "eA": {
                    "subject": "creativeQuerySubject",
                    "object": "nA",
                    "predicates": ["biolink:entity_regulates_entity"],
                    "qualifier_constraints": [{
                        "qualifier_set": [
                            {"qualifier_type_id": "object_aspect",
                             "qualifier_value": "expression"
                             }]
                        }]
                },
                "eB": {
                    "subject": "nA",
                    "object": "creativeQueryObject",
                    "predicates": ["biolink:causes"]
                }
            }
        }
    }
}
```

</details>

<details>
<summary>QNode constraints (chem must be above stage 1 clinical trial)</summary>
trying to find chem that regulate the gene's expression

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "creativeQuerySubject": {
                    "categories":["biolink:ChemicalEntity"],
                    "constraints": [{
                        "id": "biolink:drug_regulatory_status_world_wide", 
                        "name": "clinical trial level",
                        "operator": ">",
                        "value": 1
                        }]
                },
                "nA": {
                    "categories":["biolink:DiseaseOrPhenotypicFeature"],
                    "is_set": true
                },
                "creativeQueryObject": {
                    "ids":["MONDO:0005147"],
                    "categories":["biolink:DiseaseOrPhenotypicFeature"],
                    "name": "type 1 dm"
               }
            },
            "edges": {
                "eA": {
                    "subject": "creativeQuerySubject",
                    "object": "nA",
                    "predicates": ["biolink:treats"]
                },
                "eB": {
                    "subject": "nA",
                    "object": "creativeQueryObject",
                    "predicates": ["biolink:subclass_of"]
                }
            }
        }
    }
}
```

</details>

<br>

[Permit unlimited recursion of attributes](https://github.com/NCATSTranslator/ReasonerAPI/commit/6ec8ea28f3262ac163803622017bb651a4adac33). 
* [x] Check that BTE doesn't have an issue with attributes being super-nested (sub-sub-attributes). 
    * status: NOT IRL TESTED since I didn't search for a TRAPI 1.3 KP that is doing this yet (to use for checking). 

<br>

[Added NodeBinding.Attributes](https://github.com/NCATSTranslator/ReasonerAPI/pull/312/files). 
   * [x] Check: does BTE ignore attributes on result node_bindings and edge_bindings? Yep. Jackson confirmed [below](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1189247850)
      * status: NOT IRL TESTED since NO TRAPI KPs told us that they were using this.
   * [x] EDIT: not doing this since we bundle Records from many KPs to make the Results: ~"BTE passes along this stuff if it comes from the TRAPI KPs (aka "doesn't ignore, keeps, and doesn't do anything with it")"~
   * [x] Checked: [So far](https://ncatstranslator.slack.com/archives/CSS752SB0/p1658496601100859), it looks like TRAPI KPs don't plan to use this. The ARAX UI team is open to showing these, when given examples of tools using them. 

<br>

batch_size_limit and rate_limit. Batch_size_limit [meaning](https://github.com/NCATSTranslator/ReasonerAPI/commit/ad3c16a3ecc085cc041b0ebbeeb7f0803e054fd0) is clarified. These seem to be [optional](https://github.com/NCATSTranslator/translator_extensions/pull/17#issuecomment-1169338189) for the x-trapi schema. 

EDIT: We continue to discuss this in later posts in this issue. 

* On-hold: BTE handling these on TRAPI KPs. 
    * We don't know which TRAPI KPs will advertise this. Once we know, we can consider automatically importing this info and using it to handle how many IDs we send in 1 sub-query (aka number of IDs on 1 QNode) and the speed that we send sub-queries (right now, it's a batching process but not really a rate/speed thing...)
    * [Jackson has been exploring](https://suwulab.slack.com/archives/CC218TEKC/p1658519526562329?thread_ts=1658337957.629909&cid=CC218TEKC) how to do the point above. It seems kinda complicated for the rate-limit (batch_size_limit seems kinda doable)
* [x] Colleen [talks](https://suwulab.slack.com/archives/CC218TEKC/p1658520776257729?thread_ts=1658507462.159719&cid=CC218TEKC) to Jackson about what rate_limit to advertise for BTE / Service-Provider-TRAPI
* Ignoring: batch_size_limit for BTE (both for api-specific / team-specific behaving as KPs, AND the main endpoint acting as an ARA). This isn't directly connected to the "exploding" response issue, and so we'd only be able to add an arbitrary limit (like having >= 20 IDs on 1 QNode seems like a bit much). 

---

### Discussion still needed

Error codes related to limits 413 / 429. See [comparison](https://github.com/NCATSTranslator/ReasonerAPI/compare/v1.2.0...1.3#) / [section](https://github.com/NCATSTranslator/ReasonerAPI/blob/1d2fe13f8f7fa7943c729f82878c3b4bee842aa3/TranslatorReasonerAPI.yaml#L118) of TRAPI 1.3
* [x] Jackson is working on it, starting with exploring (see the batch_size_limit / rate_limit discussion above) 

EDIT: We continue to discuss this in later posts in this issue. 

<br>

submitter property in TRAPI query. See [comparison](https://github.com/NCATSTranslator/ReasonerAPI/compare/v1.2.0...1.3#) / [section](https://github.com/NCATSTranslator/ReasonerAPI/blob/1d2fe13f8f7fa7943c729f82878c3b4bee842aa3/TranslatorReasonerAPI.yaml#L241) of TRAPI 1.3. [Optional](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1189311751)
* [x] Check: are we using this - and if so, are we using the correct format of value in it? EDIT: no format for its values right now
* [x] [Modifying](https://suwulab.slack.com/archives/CC218TEKC/p1658524799223579?thread_ts=1658337957.629909&cid=CC218TEKC) what we put down for it?

EDIT: We continue to discuss this in later posts in this issue. 

<br>

EDIT: moving text that was below to other issues.

**Comment by tokebe** [comment]
Based on recent discussion, it appears that ancestor expansion for the MetaKG is not required. With that off the list, the high priority tasks should be completed, pending some additional verification testing.

Additional notes for now:

- `knowledge_type: lookup`: No additional implementation necessary. Lookup behavior is the default behavior, if lookup is provided, the the special cases for creative are not tripped, so default lookup behavior occurs. (Re-confirmed, nothing breaks, either.)

**Comment by tokebe** [comment]
Presently it appears that BTE ignores attributes on node_bindings and edge_bindings. Is discussion required about BTE's handling of this?

**Comment by tokebe** [comment]
Currently we don't use submitter, but providing it doesn't break anything -- do we want to use it for anything? The TRAPI spec doesn't appear to require that we return it, so we can theoretically ignore it for now.

**Comment by colleenXu** [comment]
My thoughts on what's left:

* Taking some time to go through these lists in detail and discuss what's left / what to do about it would be good. 

* Richard B (SRI) reached out to me over the test_data_location / SRI-testing-harness format. I think the format for ARAs isn't set yet, and I discussed the nuances of asking for test triples for non-TRAPI stuff. It seems like we'd only provide test-triples for "Service Provider TRAPI" and can use the testExamples comments on operations to compile the list...

**Comment by colleenXu** [comment]
Note:
* CHP is an example of a TRAPI KP that plans to use query_id in results (aka node-expansion stuff where the "id" field of the results won't match what was asked). Internal Translator Slack [link](https://ncatstranslator.slack.com/archives/CSS752SB0/p1658500521570019?thread_ts=1658496601.100859&cid=CSS752SB0)

**Comment by colleenXu** [comment]
Note on the migration:

* May need to watch whether TRAPI KPs move to different registrations for their 1.3 / latest tools. See notes https://github.com/biothings/BioThings_Explorer_TRAPI/pull/467#issuecomment-1195031331 and https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472

**Comment by colleenXu** [comment]
Currently still pending from this [master-post](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1176496343) of not-high-priority stuff:

* Error codes related to limits 413 / 429 and submitter property. Discussed in internal lab Slack. Probably related to #479 
    * BTE sending error codes to others is done ([Jackson](https://suwulab.slack.com/archives/CC218TEKC/p1658416331730739?thread_ts=1658337957.629909&cid=CC218TEKC))
        * BTE doesn't need to send a 413 because we're not doing batch size limits (on requests to BTE)
        * BTE already sends a 429 when the rate limit is exceeded
    * Jackson is exploring how to handle it if other TRAPI KPs sent us these error codes. This is still somewhat theoretical (do they advertise their limits? do we ingest/know of those limits? how do we even [respect](https://suwulab.slack.com/archives/CC218TEKC/p1658519526562329?thread_ts=1658337957.629909&cid=CC218TEKC) those limits across BTE multiprocessing stuff/diff instances simultaneously doing stuff?)
    * noting that this is useful for understanding what these limits are: https://github.com/NCATSTranslator/translator_extensions/pull/11/files and https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/ImplementationRules.md#infox-trapibatch_size_limit

---

To-do (for me):
* [x] [current](https://github.com/NCATS-Tangerine/translator-api-registry/tree/bte-trapi1.3) branch. Make trapi1.3 branch in registry: update bte / service provider yamls. Mentioned [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472#issuecomment-1197094622). 
    * [x] EDIT: decided not to do for QNode since people often put "name" there. set additional properties on ~[QNode](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/ImplementationRules.md#qnodexxxxx)~ QEdge to false. This would fulfill what we want to do for that TRAPI implementation note
    * [x] [rate_limit](https://suwulab.slack.com/archives/CC218TEKC/p1658346168168389?thread_ts=1658337957.629909&cid=CC218TEKC) [advertised](https://suwulab.slack.com/archives/CC218TEKC/p1658520776257729?thread_ts=1658507462.159719&cid=CC218TEKC)?
* [x] [currently](https://github.com/biothings/BioThings_Explorer_TRAPI/commit/c5111a0f588efc39857fd0fc47c5f9da547c5443) added. add the changes mentioned above to the bte-trapi trapi1.3 branch's smartapi yaml. Can then test whether we stop execution/give error on constraint-related stuff. Mentioned [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472#issuecomment-1197094622). 
* [x] (ongoing, Part of #472) Review BTE's TRAPI-KP list in API_LIST (bte-trapi) -> replace entries with TRAPI 1.3 versions in registry.  
    * [COHD](http://smart-api.info/registry?q=cedcb1004b56533d1e6901319693b778) has a TRAPI 1.3 registration for dev (non-ITRB) only. 
    * Automat has TRAPI 1.3 registrations (non-ITRB dev), and has a "too many registrations" issue. Look [here](https://smart-api.info/registry?q=automat) and sort by alphabetical A->Z
    * CHP has 1 registration that is not TRAPI 1.3
* [x] see #482. Open an issue around constraints (and close the old issues)...
* [x] see #481. Open an issue around SRI testing harness (remove section from this issue huge message).
* [x] see https://github.com/biothings/bte-auto-demos/issues/13. comment on or open issue around the suite of queries for tests.

**Comment by tokebe** [comment]
- 429 from KPs is handled in https://github.com/biothings/call-apis.js/compare/trapi1.3
  - BTE skips 429 queries until `retry-after` has passed
- 413 was agreed on to wait until we see KPs advertising limits I believe? As it's easier to avoid than to handle (currently, it's handled by marking the query as failed)
- Will push a commit to add submitter property changes

**Comment by tokebe** [comment]
Added submitter handling. New Behavior:

- Always start with `infores:bte`
- If `INSTANCE_ENV` defined, attach x-maturity (for example, `infores:bte; bte-dev`)
- If original query had `submitter`, include this information (for example, `infores:bte; subquery for client "clientSubmitterProperty"`

Each of these can combine, so you could get `infores:bte; bte-dev; subquery for client "clientSubmitterProperty"` (will always be in this order).

**Comment by colleenXu** [comment]
Noting `trapi1.3` branches in:
* [bte-trapi](https://github.com/biothings/BioThings_Explorer_TRAPI/tree/trapi1.3)
* [call-apis](https://github.com/biothings/call-apis.js/tree/trapi1.3)
* [query-handler](https://github.com/biothings/bte_trapi_query_graph_handler/tree/trapi1.3)
* [smartapi-kg](https://github.com/biothings/smartapi-kg.js/tree/trapi1.3)? 

and this [branch](https://github.com/NCATS-Tangerine/translator-api-registry/tree/bte-trapi1.3) in translator-api-registry

**Comment by colleenXu** [comment]
@tokebe on the [limits](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1209447559)/413 thing: COHD TRAPI 1.3 (which the trapi1.3 branch uses) does set a rate_limit and a batch_limit. Pretty stringent ones too...the [yaml](https://raw.githubusercontent.com/WengLab-InformaticsResearch/cohd_api/TRAPI_1.3_Updates/cohd/TranslatorReasonerAPI.yaml) linked in the [registration](http://smart-api.info/registry?q=cedcb1004b56533d1e6901319693b778) says batch_size_limit is 10 (aka 10 ids per QNode in a query or only 10 IDs per batch for our subquerying?) and rate_limit is 10 (10 requests/client/min?)

I don't see any examples of batch_size_limit or rate_limit for Automat KPs right now (https://automat.renci.org/biolink/1.3/openapi.json)

---

Also I'm not sure that TRAPI KPs provide `retry-after`, or what this is (maybe it's my lack of knowledge >.<) https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1209447559

And I can't tell that this [feature](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1209797443) is being done...(maybe I can tell by running BTE using VSCode...) so I'll take your word for it. 

I went through the entire issue and tested each feature / added comments.

**Comment by tokebe** [comment]
For the units, [that would appear to be the case](https://github.com/NCATSTranslator/ReasonerAPI/pull/294#issuecomment-919257380). I'll get to work seeing how best to handle these limits. I imagine rate limiting will be the more complicated issue...

[`retry-after`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) is an HTTP header typically sent along with a 429 response. It's not guaranteed but is extremely common in automated rate-limiting, so it's worth having implemented. It can be integer seconds or a date after which to try again -- my code accounts for either.

I tested the `submitter` feature by way of breakpoints when the query config is accessed prior to making the subquery, so I can confirm it's working (at least that much testing is standard practice for me...).

**Comment by tokebe** [comment]
I've implemented support for `batch_size_limit`. Please note that there is now a [smartapi-kg `trapi1.3` branch](https://github.com/biothings/smartapi-kg.js/tree/trapi1.3) in order to support this.

Rate limit support is surprisingly complex to implement, due to both the nature of query batches and the fact that BTE has multiple processes and threads operating at any given time, each of which would theoretically query from the same API and use a separate internal rate-limit count on query-execution level (to say nothing of the fact that our pm2 config maintains 3 instances on the same IP).

I propose a two-pronged solution:
- Primary: Use an expiring, incrementing redis key per-API when a request is made. If the key is at the limit, wait for it to expire before executing, and then re-create the key (these operations can be protected by a lock so no race conditions arise).
- Secondary: If redis is unavailable, attempt to use a naive delay, where BTE simply inserts a delay that *should* account for the rate limit, assuming typical conditions (such as each queue and multiple sync threads NOT also attempting to query). This wouldn't guarantee perfect behavior, but should really only ever be seen in non-redis local testing and should therefore be acceptable.

I'm working on implementing these. Feel free to comment on whether this approach should be modified.

**Comment by tokebe** [comment]
Rate limiting has been implemented using the above proposal. A clarification: the redis-based limiter uses a rolling window, which uses slightly more memory to manage, but shouldn't ever become unwieldy in realistic scenarios.

**Comment by colleenXu** [comment]
Did a quick test. It looked to me like the batch_size_limit was working for COHD (10 IDs per query), and console logs said that the [secondary](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1212381186)/naive approach was being used for the rate_limit (`API COHD TRAPI 1.3 - DEVELOPMENT is rate-limited. Using naive strategy (waiting 6000ms)... +0ms`). 

So yay!

**Comment by colleenXu** [comment]
We may need to change the SmartAPI yamls and some behavior for TRAPI 1.3, depending on:
* https://github.com/NCATSTranslator/ReasonerAPI/pull/365
* and any differences / merged-PRs in the trapi 1.3.0-beta tagged stuff https://github.com/NCATSTranslator/ReasonerAPI/commits/v1.3.0-beta

**Comment by colleenXu** [comment]
The issue I raised [above](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1217494301) has been addressed (see https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472#issuecomment-1230859289). 

I think we can close this issue since all features have been addressed or are in separate issues like 
https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472
https://github.com/biothings/BioThings_Explorer_TRAPI/issues/482 (constraints, and a bit on qualifiers for now)
https://github.com/biothings/BioThings_Explorer_TRAPI/issues/494
